import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import Landing from '../modules/landing'
import Navbar from '../components/layout/Navbar'
import { useContext } from 'react'
import { AppContext } from '../components/layout/context/AppProvider'
import Hamburger from '../components/layout/Hamburger'
import Drawer from '../components/layout/Drawer'

export default function Home() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* <Navbar /> */}
            <Hamburger />
            <Drawer />
            <Landing />
        </>
    )
}
